# Generated by Django 6.0 on 2025-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reel_reelcomment_reellike'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
