# Generated by Django 6.0 on 2025-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reel_shares_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
